### ISSUE TITLE
Salesforce: Do we need a way to test the API status; maybe make automatic refreshes?

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#4]
This could easily be done as part of the now functional queue system (daily, for example), but it's unclear to me whether it's necessary or not.

This fits into a larger question around performance of the Salesforce API.

**Comment by jonathanstegall** [comment]
The way the Drupal module handles it is described here: https://www.drupal.org/node/2631122

While part of the issue mentioned is indeed a permissions issue, and we have that solved, there's also this part:

'''
Aaron, I misunderstood your suggestion. Trigger a Salesforce API call in a hook_cron to keep the token alive. That is an excellent idea.
'''

**Comment by jonathanstegall** [comment]
There are times when I open my computer in the morning and it tries to run the `salesforce_pull` cron job, and it results in this:

```
[29-Nov-2016 23:23:22 UTC] PHP Fatal error:  Uncaught exception 'SalesforceException' with message 'Unable to get a Salesforce access token.' in /wp-content/plugins/salesforce-rest-api/classes/salesforce.php:502
Stack trace:
#0 /wp-content/plugins/salesforce-rest-api/classes/salesforce.php(169): Salesforce->refresh_token()
#1 /wp-content/plugins/salesforce-rest-api/classes/salesforce.php(687): Salesforce->api_call('query?q=SELECT+...', Array, 'GET', Array)
#2 /wp-content/plugins/salesforce-rest-api/classes/salesforce_pull.php(277): Salesforce->query('SELECT Descript...', Array)
#3 /wp-content/plugins/salesforce-rest-api/classes/salesforce_pull.php(103): Salesforce_Pull->get_updated_records()
#4 /wp-content/plugins/salesforce-rest-api/classes/schedule.php(222): Salesforce_Pull->salesforce_pull()
#5 /wp-content/plugins/salesforce-rest-api/classes/salesforce.php on line 502
```

I think this is because the token has expired. However this never happens during the course of a workday, so it may be a non issue for a server that is always awake and connected to the internet.

**Comment by jonathanstegall** [comment]
The same error happened during a day where I made no requests to WordPress all day. Maybe it is that the token gets refreshed if the connection is being used but otherwise it does not.

**Comment by jonathanstegall** [comment]
The error discussed above seems to have stopped happening.

At this point, the issue that could possibly require a change is that when an admin setting (for example) that needs to load Salesforce data is viewed, it is really slow when it goes to restore the contents from the API the first time. This is presumably because it needs to 1) authenticate itself if the token has expired, and 2) make the API call(s).

I think the ideal would be for the plugin to go around refreshing the token as a cron item, but I'm still unclear on whether that is correct.

**Comment by jonathanstegall** [comment]
Oh, that error still does happen occasionally. Not every day though. Presumably still during a cron run, but unclear why.

'''
[17-Apr-2017 21:33:46 UTC] PHP Fatal error:  Uncaught exception 'SalesforceException' with message 'Unable to get a Salesforce access token.' in /wp-content/plugins/salesforce-rest-api/classes/salesforce.php:526
Stack trace:
#0 /wp-content/plugins/salesforce-rest-api/classes/salesforce.php(176): Salesforce->refresh_token()
#1 /wp-content/plugins/salesforce-rest-api/classes/salesforce.php(704): Salesforce->api_call('query?q=SELECT+...', Array, 'GET', Array)
#2 /wp-content/plugins/salesforce-rest-api/classes/salesforce_pull.php(236): Salesforce->query('SELECT Email, F...', Array)
#3 /wp-content/plugins/salesforce-rest-api/classes/salesforce_pull.php(109): Salesforce_Pull->get_updated_records()
#4 /wp-content/plugins/salesforce-rest-api/classes/schedule.php(228): Salesforce_Pull->salesforce_pull()
#5 / in /wp-content/plugins/salesforce-rest-api/classes/salesforce.php on line 526
```

**Comment by benlk** [comment]
When that exception is thrown, the plugin passes two arguments: `$message` and `$code`: https://github.com/MinnPost/object-sync-for-salesforce/blob/7ba99c3ae0c52897bc5cb7978bf1cf61c97cec53/classes/salesforce.php#L538

> [17-Apr-2017 21:33:46 UTC] PHP Fatal error: Uncaught exception 'SalesforceException' with message 'Unable to get a Salesforce access token.' in /wp-content/plugins/salesforce-rest-api/classes/salesforce.php:526

But in this log entry, it looks like it's only emitting the message. The code is an HTTP error code; do we want to add that error code to the exception's message?

**Comment by jonathanstegall** [comment]
@benlk sure, you can put the code in there. I think it's a 401. Can't remember though.

**Comment by benlk** [comment]
Have you seen this error since? I saw it the day after that PR, but apparently I wasn't running an up-to-date branch?

> 2017/05/19 11:26:33 [error] 44357#0: *1702 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught SalesforceException: Unable to get a Salesforce access token. in /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php:538
Stack trace:
#0 /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(179): Salesforce->refresh_token()
#1 /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(718): Salesforce->api_call('query?q=SELECT+...', Array, 'GET', Array)
#2 /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/salesforce_pull.php(183): Salesforce->query('SELECT WhoId, S...', Array)
#3 /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/salesforce_pull.php(110): Salesforce_Pull->get_updated_records()
#4 /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/schedule.php(228): Salesforce_Pull->salesforce_pull()
#5 /Users/blk/" while reading response header from upstream, client: 127.0.0.1, server: minnpost-testing.invalid, request: "POST /wp-cron.php?doing_wp_cron=1495207593.4259300231933593750000 HTTP/1.1", upstream: "fastcgi://unix:/Users/blk/.valet/valet.sock:", host: "minnpost-testing.invalid", referrer: "https://minnpost-testing.invalid/wp-cron.php?doing_wp_cron=1495207593.4259300231933593750000"

**Comment by jonathanstegall** [comment]
I actually saw something like it today. It went like this:

```
[Tue May 30 07:10:18.389855 2017] [:error] [pid 93150] [client 127.0.0.1:58040] PHP Fatal error:  Uncaught Object_Sync_Sf_Exception: Unable to get a Salesforce access token. Salesforce returned the following errorCode: 0 in /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php:570\nStack trace:\n#0 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(181): Object_Sync_Sf_Salesforce->refresh_token()\n#1 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(142): Object_Sync_Sf_Salesforce->api_call('https://cs42.sa...', Array, 'GET', Array)\n#2 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admin.php(1291): Object_Sync_Sf_Salesforce->get_api_versions()\n#3 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admin.php(496): Object_Sync_Sf_Admin->version_options()\n#4 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admi in /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php on line 570, referer: https://vanilla-wordpress.dev/wp-admin/edit.php?post_type=wp_log
[Tue May 30 07:10:18.656805 2017] [:error] [pid 99258] [client 127.0.0.1:58045] PHP Fatal error:  Uncaught Object_Sync_Sf_Exception: Unable to get a Salesforce access token. Salesforce returned the following errorCode: 0 in /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php:570\nStack trace:\n#0 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(181): Object_Sync_Sf_Salesforce->refresh_token()\n#1 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(763): Object_Sync_Sf_Salesforce->api_call('query?q=SELECT+...', Array, 'GET', Array)\n#2 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce_pull.php(185): Object_Sync_Sf_Salesforce->query('SELECT Email, F...', Array)\n#3 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce_pull.php(112): Object_Sync_Sf_Salesforce_Pull->get_updated_records()\n#4 /Users/jstegall/Sites/vanilla-wordpress/wp-conten in /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php on line 570, referer: https://vanilla-wordpress.dev/wp-cron.php?doing_wp_cron=1496146203.4210309982299804687500
[Tue May 30 07:10:18.788190 2017] [:error] [pid 82171] [client 127.0.0.1:58038] PHP Fatal error:  Uncaught Object_Sync_Sf_Exception: Unable to get a Salesforce access token. Salesforce returned the following errorCode: 0 in /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php:570\nStack trace:\n#0 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(181): Object_Sync_Sf_Salesforce->refresh_token()\n#1 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(142): Object_Sync_Sf_Salesforce->api_call('https://cs42.sa...', Array, 'GET', Array)\n#2 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admin.php(1291): Object_Sync_Sf_Salesforce->get_api_versions()\n#3 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admin.php(496): Object_Sync_Sf_Admin->version_options()\n#4 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admi in /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php on line 570, referer: https://vanilla-wordpress.dev/wp-admin/user-edit.php?user_id=34&wp_http_referer=%2Fwp-admin%2Fusers.php
[Tue May 30 07:10:18.984098 2017] [:error] [pid 99052] [client 127.0.0.1:58039] PHP Fatal error:  Uncaught Object_Sync_Sf_Exception: Unable to get a Salesforce access token. Salesforce returned the following errorCode: 0 in /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php:570\nStack trace:\n#0 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(181): Object_Sync_Sf_Salesforce->refresh_token()\n#1 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(142): Object_Sync_Sf_Salesforce->api_call('https://cs42.sa...', Array, 'GET', Array)\n#2 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admin.php(1291): Object_Sync_Sf_Salesforce->get_api_versions()\n#3 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admin.php(496): Object_Sync_Sf_Admin->version_options()\n#4 /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admi in /Users/jstegall/Sites/vanilla-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php on line 570, referer: https://vanilla-wordpress.dev/wp-admin/tools.php?page=crontrol_admin_manage_page
[Tue May 30 07:10:19.354385 2017] [:error] [pid 98670] [client 127.0.0.1:58041] PHP Fatal error:  Uncaught Object_Sync_Sf_Exception: Unable to get a Salesforce access token. Salesforce returned the following errorCode: 0 in /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php:570\nStack trace:\n#0 /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(181): Object_Sync_Sf_Salesforce->refresh_token()\n#1 /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(142): Object_Sync_Sf_Salesforce->api_call('https://cs42.sa...', Array, 'GET', Array)\n#2 /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admin.php(1291): Object_Sync_Sf_Salesforce->get_api_versions()\n#3 /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/admin.php(496): Object_Sync_Sf_Admin->version_options()\n#4 /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classe in /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php on line 570, referer: https://minnpost-wordpress.dev/wp-admin/options-general.php?page=object-sync-salesforce-admin&tab=schedule
[Tue May 30 07:10:19.404671 2017] [:error] [pid 99543] [client 127.0.0.1:58044] PHP Fatal error:  Uncaught Object_Sync_Sf_Exception: Unable to get a Salesforce access token. Salesforce returned the following errorCode: 0 in /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php:570\nStack trace:\n#0 /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(181): Object_Sync_Sf_Salesforce->refresh_token()\n#1 /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(763): Object_Sync_Sf_Salesforce->api_call('query?q=SELECT+...', Array, 'GET', Array)\n#2 /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce_pull.php(185): Object_Sync_Sf_Salesforce->query('SELECT Email, F...', Array)\n#3 /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce_pull.php(112): Object_Sync_Sf_Salesforce_Pull->get_updated_records()\n#4 /Users/jstegall/Sites/minnpost-wordpress/wp- in /Users/jstegall/Sites/minnpost-wordpress/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php on line 570, referer: https://minnpost-wordpress.dev/wp-cron.php?doing_wp_cron=1496146203.5266869068145751953125
```

**Comment by benlk** [comment]
That sounds plausible. I'm in favor of closing it.

**Comment by jonathanstegall** [comment]
Works for me. We'll re open if it reappears for any other users, or in any other use cases.
