### ISSUE TITLE
When a mapping row is saved with no WordPress and no Salesforce options, the resultant API call causes an error.

### ISSUE THREAD

**Issue by benlk** [MinnPost/object-sync-for-salesforce#82]
Given the following settings:
<img width="943" alt="screen shot 2017-05-18 at 6 07 05 pm" src="https://cloud.githubusercontent.com/assets/1754187/26225431/249be2fc-3bf5-11e7-85eb-20b9f985624a.png">

The following error occurs:

```
2017/05/18 18:06:36 [error] 44359#0: *792 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught SalesforceException: 
CreatedById, Subject, Location, , Id, CreatedDate FROM Event WHERE
                               ^
ERROR at Row:1:Column:61
unexpected token: ',' in /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php:207
Stack trace:
#0 /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/salesforce.php(726): Salesforce->api_call('query?q=SELECT+...', Array, 'GET', Array)
#1 /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/salesforce_pull.php(183): Salesforce->query('SELECT WhoId, S...', Array)
#2 /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/salesforce_pull.php(110): Salesforce_Pull->get_updated_records()
#3 /Users/blk/sites/minnpost-testing/wp-content/plugins/object-sync-for-salesforce/classes/schedule.php(228): Salesforce_Pull->salesforce_pull()
#4 /Users/blk/sites/minnpost-testing/wp-content" while reading response header from upstream, client: 127.0.0.1, server: minnpost-testing.invalid, request: "POST /wp-cron.php?doing_wp_cron=1495145195.6611979007720947265625 HTTP/1.1", upstream: "fastcgi://unix:/Users/blk/.valet/valet.sock:", host: "minnpost-testing.invalid", referrer: "https://minnpost-testing.invalid/wp-cron.php?doing_wp_cron=1495145195.6611979007720947265625"
```

Should we automatically trim empty mappings from fieldmaps? They cause API errors.

**Comment by jonathanstegall** [comment]
@benlk Yes, you're totally right. Are you prepared to take care of automatically trimming, or do you want me to go in and get it?
